# Generated by Django 3.1.5 on 2021-01-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210125_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Listing',
        ),
    ]
