# Generated by Django 3.1.5 on 2021-01-31 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210131_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_listing', to='auctions.listing'),
        ),
    ]
